version: '3'
services:
  node:
    build: .
    ports:
     - "8030:80"    
    expose:
      - "80"   
    links:
      - mysql
    depends_on:
      - mysql    

  mysql:
    image: "mysql/mysql-server"
    restart: unless-stopped
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: tjdtls!
      MYSQL_DATABASE: FLOWN
      MYSQL_USER: root
      MYSQL_PASSWORD: tjdtls! 
    expose:
      - "3306"
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      #- .flown_DV:/var/lib/mysql