version: '4'
services:
  node:
    build: .
    ports:
     - "8030:80"    
    expose:
      - "80"   
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: "mysql/mysql-server"
    restart: unless-stopped
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: tjdtls!
      MYSQL_DATABASE: FLOWN
    expose:
      - "3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    networks: 
      mynetwork:  
        ipv4_address: 172.18.0.2

networks: 
  mynetwork: 
    driver: bridge  
    ipam:
      config:
        - subnet: 172.18.0.0/16
